apiVersion: apps/v1
kind: Deployment
metadata:
  name: zhui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zhui
  template:
    metadata:
      labels:
        app: zhui
    spec:
      restartPolicy: Always
      containers:
        - name: zhui
          image: zhui177/v2
          ports:
            - containerPort: 8251
            
---
apiVersion: v1
kind: Service
metadata:
  name: zhuictl
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "zhuictl"
    port: 8251
  selector:
    app: zhui
